### ISSUE TITLE
Maybe issue with nanodump -write

### ISSUE THREAD

**Issue by ghost** [helpsystems/nanodump#18] opened 2022-04-26 14:40 UTC
REF issue on other repo https://github.com/skelsec/pypykatz/issues/101

I have run into this when using tool. 

Let me know what/if any feedback is needed. 

`restore_signature.sh` was run without error on file.

1 Beacon did basically DOS shell with `The dump file is too big. please increase DUMP_MAX_SIZE.` this occurred on 1 of 2 tests.

**Comment by S4ntiagoP** [comment] 2022-04-26 14:47
You need to increase the DUMP_MAX_SIZE variable, you can find it [here](https://github.com/helpsystems/nanodump/blob/main/include/nanodump.h#L26).
Then, recompile with `make -f Makefile.mingw` and try again.

As for the issue regarding pypykatz, I really can't tell you much, why don't you:
- Dump LSASS using the task manager and see if the error persists with that dump
- Try with an older version of pypykatz
- Send ([here](https://nx5494.your-storageshare.de/s/SJteWj3PPbg8jBA)) the dump to skelsec to help him find the parsing issue (assuming there is one)

**Comment by S4ntiagoP** [comment] 2022-05-04 12:15
Ok I'm closing this, I cannot reproduce the issue with the infinite loop in pypykatz and the DUMP_MAX_SIZE is simple enough to fix.
If you have new information feel free to re-open this.

**Closed as completed by S4ntiagoP** 2022-05-04 12:15 UTC
